import './globals.css';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'MindState',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            {/* <SignedOut>
              <Link href="/journal">
                <SignInButton />
              </Link>
            </SignedOut> */}
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
